# Generated by Django 4.0.4 on 2022-05-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_money',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
