# Generated by Django 4.0.4 on 2022-05-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_email_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login_with_gg',
            field=models.BooleanField(default=False),
        ),
    ]
