# Generated by Django 4.0.4 on 2022-06-14 09:05

from django.db import migrations, models
import transaction.constants.TransConstants


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency_unit',
            field=models.CharField(choices=[('USD', 'USD'), ('VND', 'VND')], default=transaction.constants.TransConstants.ValueCurrency['VND'], max_length=100),
        ),
    ]
