# Generated by Django 4.0.4 on 2022-06-21 07:57

from django.db import migrations, models
import transaction.constants.TransConstants


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_currency_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency_unit',
            field=models.CharField(choices=[('VND', 'VND')], default=transaction.constants.TransConstants.ValueCurrency['VND'], max_length=100),
        ),
    ]
