# Generated by Django 4.0.4 on 2022-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_currency_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
