# Generated by Django 4.0.4 on 2022-05-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_email_alter_account_email_and_more'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.typetransaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
