# Generated by Django 4.0.4 on 2022-06-14 03:58

from django.db import migrations, models
import transaction.constants.TransConstants


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_type_alter_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='avatar',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currencyUnit',
            field=models.CharField(choices=[('USD', 'USD'), ('VND', 'VND')], default=transaction.constants.TransConstants.ValueCurrency['VND'], max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CANCELED', 'CANCELED'), ('COMPLETED', 'COMPLETED')], default=transaction.constants.TransConstants.TransStatus['COMPLETED'], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='typetransaction',
            name='isIncreased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
