# Generated by Django 4.0.4 on 2022-06-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_transaction_avatar_transaction_currencyunit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='currencyUnit',
            new_name='currency_unit',
        ),
    ]
