# Generated by Django 4.0.4 on 2022-06-21 07:57

from django.db import migrations, models
import transaction.constants.TransConstants


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency_unit',
            field=models.CharField(choices=[('VND', 'VND')], default=transaction.constants.TransConstants.ValueCurrency['VND'], max_length=100),
        ),
    ]
