# Generated by Django 4.0.4 on 2022-06-25 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 25, 4, 26, 27, 599071), null=True),
        ),
    ]
