# Generated by Django 4.0.4 on 2022-06-25 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 25, 6, 46, 45, 920927), null=True),
        ),
    ]
