# Generated by Django 4.0.4 on 2022-06-21 09:19

from django.db import migrations, models
import django.db.models.deletion
import saving_money.constants.DailyConstants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_alter_user_currency_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('money_goal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('saving_money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily', models.CharField(choices=[('DAY', 'DAY'), ('WEEK', 'WEEK'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR')], default=saving_money.constants.DailyConstants.DailyStatus['WEEK'], max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
