# Generated by Django 4.0.4 on 2022-06-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saving_money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneys', models.DecimalField(decimal_places=2, max_digits=20)),
                ('note', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving_money.savingmoney')),
            ],
        ),
    ]
