# Generated by Django 4.0.4 on 2022-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_money', '0002_savetrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingmoney',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
