# Generated by Django 4.0.4 on 2022-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_money', '0003_savingmoney_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingmoney',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
