# Generated by Django 4.0.4 on 2022-06-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving_money', '0004_savingmoney_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savetrans',
            old_name='moneys',
            new_name='money',
        ),
    ]
